# Generated by Django 5.2.1 on 2025-05-16 08:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('link', models.URLField(max_length=255)),
            ],
            options={
                'db_table': 'brands',
            },
        ),
        migrations.CreateModel(
            name='Configuration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('link', models.URLField(max_length=255)),
                ('engine_name', models.CharField(blank=True, max_length=100, null=True)),
                ('date_start', models.CharField(max_length=11)),
                ('date_end', models.CharField(max_length=11)),
            ],
            options={
                'db_table': 'configurations',
            },
        ),
        migrations.CreateModel(
            name='Generation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('link', models.URLField(max_length=255)),
                ('body_code', models.CharField(blank=True, max_length=100, null=True)),
                ('body_type', models.CharField(blank=True, max_length=100, null=True)),
                ('is_hybrid', models.BooleanField(default=False)),
                ('generation_num', models.IntegerField()),
                ('restyling_num', models.IntegerField()),
                ('date_start', models.CharField(max_length=11)),
                ('date_end', models.CharField(max_length=11)),
            ],
            options={
                'db_table': 'generations',
            },
        ),
        migrations.CreateModel(
            name='CarData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('front_tires', models.CharField(max_length=50)),
                ('rear_tires', models.CharField(max_length=50)),
                ('engine_capacity', models.FloatField()),
                ('engine_power_hp', models.IntegerField()),
                ('engine_power_kw', models.IntegerField()),
                ('consumption', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fuel_type', models.CharField(max_length=50)),
                ('transmission', models.CharField(max_length=50)),
                ('driver_type', models.CharField(max_length=50)),
                ('seats_count', models.IntegerField()),
                ('doors_count', models.IntegerField()),
                ('clearance', models.IntegerField()),
                ('trunk_volume', models.IntegerField()),
                ('configuration', models.ForeignKey(db_column='configuration_id', on_delete=django.db.models.deletion.DO_NOTHING, to='cars.configuration')),
            ],
            options={
                'db_table': 'car_data',
            },
        ),
        migrations.AddField(
            model_name='configuration',
            name='generation',
            field=models.ForeignKey(db_column='generation_id', on_delete=django.db.models.deletion.DO_NOTHING, to='cars.generation'),
        ),
        migrations.CreateModel(
            name='Model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('link', models.URLField(max_length=255)),
                ('brand', models.ForeignKey(db_column='brand_id', on_delete=django.db.models.deletion.DO_NOTHING, to='cars.brand')),
            ],
            options={
                'db_table': 'models',
            },
        ),
        migrations.AddField(
            model_name='generation',
            name='model',
            field=models.ForeignKey(db_column='model_id', on_delete=django.db.models.deletion.DO_NOTHING, to='cars.model'),
        ),
    ]
