# Generated by Django 5.2.1 on 2025-05-21 01:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cardata',
            options={'verbose_name': 'Car Data', 'verbose_name_plural': 'Car Data'},
        ),
        migrations.RenameField(
            model_name='cardata',
            old_name='driver_type',
            new_name='drive_type',
        ),
    ]
