# Generated by Django 5.2.1 on 2026-05-10 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cardata',
            name='body_mark',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
