# Generated by Django 5.2.1 on 2026-05-14 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0002_cardata_body_mark'),
    ]

    operations = [
        migrations.AddField(
            model_name='protocolmeasurement',
            name='glonass_button_present',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
