# Generated by Django 5.2.1 on 2026-05-14 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0003_protocolmeasurement_glonass_button_present'),
    ]

    operations = [
        migrations.AddField(
            model_name='protocol',
            name='dash_fields',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='protocolbrake',
            name='dash_fields',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='protocollight',
            name='dash_fields',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='protocolmeasurement',
            name='dash_fields',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='protocolpowersupply',
            name='dash_fields',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='protocolroadcondition',
            name='dash_fields',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='protocoltestcondition',
            name='dash_fields',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
