# Generated by Django 5.2.1 on 2026-05-22 14:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0004_protocol_dash_fields_protocolbrake_dash_fields_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='protocol',
            name='locked_at',
            field=models.DateTimeField(blank=True, db_column='locked_at', null=True),
        ),
        migrations.AddField(
            model_name='protocol',
            name='locked_by',
            field=models.ForeignKey(blank=True, db_column='locked_by_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='locked_protocols', to=settings.AUTH_USER_MODEL),
        ),
    ]
