# Generated by Django 5.2.1 on 2026-04-17 00:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0004_alter_model_id_alter_protocol_car_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Measurement',
        ),
    ]
