# Generated by Django 5.2.1 on 2026-05-23 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0005_protocol_locked_at_protocol_locked_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='protocol',
            name='manufacturer_info',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='protocol',
            name='owner_first_name',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='protocol',
            name='owner_last_name',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='protocol',
            name='owner_middle_name',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
