# Generated by Django 5.2.1 on 2026-05-26 01:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0006_protocol_manufacturer_info_protocol_owner_first_name_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='protocol',
            name='cancelled_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='protocol',
            name='cancelled_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cancelled_protocols', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='protocol',
            name='returned_for_revision',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='protocol',
            name='revision_comment',
            field=models.TextField(blank=True, null=True),
        ),
    ]
